### PR TITLE
Fix work with CodeMirror 3

### PR DESCRIPTION
**Pull request by qodunpob**

### CODE REVIEW

**Comment by lkcampbell** [comment]
I second this pull request :).  I want to try out this extension but it doesn't work in the current version of Brackets.

**Comment by wernerglinka** [comment]
@toshsharma, Hi there. I am investigating how to store meta data between session for a documents. Since you have in your TODO list an item on preserving bookmarks I am wondering whether you could point me in the direction of where to look. Do you plan to use local storage or is there a brackets API for storing meta data? I would appreciate any pointers.

**Comment by lkcampbell** [comment]
@wernerglinka, Brackets has a module called "preferences/PreferencesManager" that you can use to store data between Bracket Sessions.

There are lots of examples in various extensions.  My [indent guides extension](https://github.com/lkcampbell/brackets-indent-guides) is a fairly short piece of code that uses PreferencesManager if you would like an example.  It only uses one property (enabled) but you can easily expand it.

**Comment by wernerglinka** [comment]
Thank you Lance. I appreciate the pointer.

**Pull request merged**
